# Generated by Django 3.0.4 on 2020-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRecord',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField()),
                ('precinct', models.CharField(blank=True, max_length=10, null=True)),
                ('candidate', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'challenge_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.TextField()),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'uploaded_file',
                'managed': False,
            },
        ),
    ]
