# Generated by Django 3.0.4 on 2020-03-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('precinct', models.CharField(blank=True, max_length=45, null=True)),
                ('candidate', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'candidate_info',
                'managed': False,
            },
        ),
    ]
